server {
	# wait on IPv4 and IPv6, respond to https
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name localhost;

	# setting TLS
    ssl_protocols TLSv1.2 TLSv1.3;
	# Location of the certificate
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    root /var/www/html;
    index index.php index.html index.htm;

	# Routing
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

	# If a PHP request is received, forward it to port 9000
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}